---@class PolychromeState
---@field current_colorscheme Colorscheme? The currently applied colorscheme
---@field preview_colorscheme Colorscheme? The colorscheme currently being used for preview mode
---@field preview_is_active boolean Is preview mode active?
---@field osc_groups {[string]: Group?} The autogenerated highlight groups populated by data from OSC queries
local M = {}

M.current_colorscheme = nil
M.preview_colorscheme = nil
M.preview_is_active = false
M.osc_groups = {}

return M
